#API替换相关配置。
ibiz:
  enablePermissionValid: false
  auth:
    #本地用户认证：IBZZTUserService
    #UAA认证：IBZUAAUserService
    service: IBZZTUserService
    token:
    # 本地ZT账户认证模式：SimpleTokenUtil
    # UAA认证模式：UAATokenUtil
      util: SimpleTokenUtil
  # 本地模式,缓存设置为L1
  # UAA模式,缓存设置为L2
  cacheLevel: L1
