version: "3.2"
services:
  zentaopms:
    image: ibizlab/zentaopms:12.3.1
    volumes:
      - $PWD/file:/app/zentaopms/www/data/upload/1
    networks:
      - agent_network
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
      - 80:80
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

  nacos:
    image: nacos/nacos-server:latest
    volumes:
      - $PWD/standalone-logs/:/home/nacos/logs
      - $PWD/init.d/custom.properties:/home/nacos/init.d/custom.properties
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
    networks:
      - agent_network
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

networks:
  agent_network:
    attachable: true
