version: "3.2"
services:
  ibizpms-app-web:
    image: ibizlab/ibizpms-app-web:v1
    volumes:
      - "$PWD/file:/app/file"
    ports:
      - "8102:8102"
    networks:
      - agent_network
    environment:
      - TZ=Asia/Shanghai
      - SERVER_PORT=8102
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=$IP
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=$IP:8848
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://zentaopms:3306/zentao?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      - SPRING_DATASOURCE_defaultSchema=zentao
      - SPRING_DATASOURCE_isSyncDBSchema=false
      - IBZ_SLEEP=30
      - IBIZ_SLEEP=30
      - zentao_url=http://zentaopms/
    depends_on:
      - ibizpms-provider-webapi
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

  ibizpms-provider-webapi:
    image: ibizlab/ibizpms-provider-webapi:v1
    volumes:
      - "$PWD/file:/app/file"
    ports:
      - "8101:8101"
    networks:
      - agent_network
    environment:
      - TZ=Asia/Shanghai
      - SERVER_PORT=8101
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=$IP
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=$IP:8848
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://zentaopms:3306/zentao?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      - SPRING_DATASOURCE_defaultSchema=zentao
      - SPRING_DATASOURCE_isSyncDBSchema=false
      - IBZ_SLEEP=30
      - IBIZ_SLEEP=30
      - zentao_url=http://zentaopms/
    depends_on:
      - zentaopms
      - nacos
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

  zentaopms:
    image: ibizlab/zentaopms:12.3.1
    volumes:
      - $PWD/file:/app/zentaopms/www/data/upload/1
    networks:
      - agent_network
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
      - 80:80
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

  nacos:
    image: nacos/nacos-server:latest
    volumes:
      - $PWD/standalone-logs/:/home/nacos/logs
      - $PWD/init.d/custom.properties:/home/nacos/init.d/custom.properties
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
    networks:
      - agent_network
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

networks:
  agent_network:
    attachable: true
